added how to run section to readme
oleting/training_ekg pull request #3
Opened 2022-10-28 08:32 UTC by plexx-dev

2022-10-28 08:51 UTC, plexx-dev commented
also fixed build dependencies :)

2022-10-28 08:51 UTC, plexx-dev commented
@oleting

2022-10-28 09:51 UTC, oleting requested changes
Python Version müsste auch die aktuelle funktionieren

2022-10-31 06:24 UTC, oleting approved these changes
Warum auch immer du die yaml für die Daten bearbeitet hast xD

2022-10-31 06:24 UTC, merged